# -*- coding: utf-8 -*-
"""UTS_Aurora Ihrish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3R3MJ0LBmmEsssz1etACKy9ORUuSBtD
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Fungsi untuk menampilkan gambar
def show_image(title, image, cmap=None):
    plt.imshow(image, cmap=cmap)
    plt.title(title)
    plt.axis('off')
    plt.show()

from google.colab import files

uploaded = files.upload()

import os

files = [f for f in os.listdir() if f.endswith(".jpg")]

print("File gambar:", files)

img1 = cv2.imread(files[0])
img2 = cv2.imread(files[1])

img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)

show_image("Gambar 1", img1)
show_image("Gambar 2", img2)

gray1 = cv2.cvtColor(img1, cv2.COLOR_RGB2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_RGB2GRAY)

show_image("Grayscale Gambar 1", gray1, cmap='gray')
show_image("Grayscale Gambar 2", gray2, cmap='gray')

brightness = 50

bright1 = cv2.convertScaleAbs(img1, beta=brightness)
bright2 = cv2.convertScaleAbs(img2, beta=brightness)

show_image("Brightness Gambar 1", bright1)
show_image("Brightness Gambar 2", bright2)

contrast = 1.5

contrast1 = cv2.convertScaleAbs(img1, alpha=contrast)
contrast2 = cv2.convertScaleAbs(img2, alpha=contrast)

show_image("Contrast Gambar 1", contrast1)
show_image("Contrast Gambar 2", contrast2)

rows, cols, _ = img1.shape

M = np.float32([
    [1, 0, 100],
    [0, 1, 50]
])

trans1 = cv2.warpAffine(img1, M, (cols, rows))
trans2 = cv2.warpAffine(img2, M, (cols, rows))

show_image("Translasi Gambar 1", trans1)
show_image("Translasi Gambar 2", trans2)

center = (cols // 2, rows // 2)

M = cv2.getRotationMatrix2D(center, 45, 1)

rot1 = cv2.warpAffine(img1, M, (cols, rows))
rot2 = cv2.warpAffine(img2, M, (cols, rows))

show_image("Rotasi Gambar 1", rot1)
show_image("Rotasi Gambar 2", rot2)

scale1 = cv2.resize(img1, None, fx=1.5, fy=1.5)
scale2 = cv2.resize(img2, None, fx=0.5, fy=0.5)

show_image("Scaling Besar", scale1)
show_image("Scaling Kecil", scale2)

flip1 = cv2.flip(img1, 1)
flip2 = cv2.flip(img2, 0)

show_image("Flip Horizontal", flip1)
show_image("Flip Vertikal", flip2)

hist1 = cv2.equalizeHist(gray1)
hist2 = cv2.equalizeHist(gray2)

show_image("Histogram Equalization 1", hist1, cmap='gray')
show_image("Histogram Equalization 2", hist2, cmap='gray')

smooth1 = cv2.GaussianBlur(img1, (9,9), 0)
smooth2 = cv2.GaussianBlur(img2, (9,9), 0)

show_image("Smoothing Gambar 1", smooth1)
show_image("Smoothing Gambar 2", smooth2)

kernel = np.array([
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
])

sharp1 = cv2.filter2D(img1, -1, kernel)
sharp2 = cv2.filter2D(img2, -1, kernel)

show_image("Sharpening Gambar 1", sharp1)
show_image("Sharpening Gambar 2", sharp2)